
server:
  port: 80
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
  reload:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

